### PR TITLE
Change frames2sec

### PR DESCRIPTION
**Pull request by urbster1**
frames2sec should be changed to incorporate longer and shorter animations where Synfig's formatting changes from "Xf" to "Xs Yf" to "Xm Ys". I've tested this with a 35 minute file and it works!

### CODE REVIEW

**Comment by urbster1** [comment]
sorry not really sure what I am doing here

**Comment by urbster1** [comment]
haha sorry, trying to figure out Git

**Comment by berteh** [comment]
looking at it for inclusion, thanks for the patch.

**Comment by berteh** [comment]
looking at #16 instead of this one... since it seems more recent.

**Pull request closed without merging**
